### ISSUE TITLE
Workflow Not Updating Changelog: Empty File Generated

### ISSUE THREAD

**Issue by Heet-Bhalodiya** [BobAnkh/auto-generate-changelog#129]
## Describe the bug

The workflow does not add changes to the `changelog`. Each time the workflow runs, it generates an empty `changelog` file. Even after making multiple commits (e.g., 4-5 commits) and then running the workflow, the `changelog` file remains unchanged.

## To Reproduce

Below is the content of my `changelog.yml` file for reference:

```yml
name: Generate changelog
on:
  release:
    types: [created, edited]
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: BobAnkh/auto-generate-changelog@v1.2.5
      with:
        REPO_NAME: 'my repo name'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: 'CHANGELOG.md'
        BRANCH: test-changelog
        COMMIT_MESSAGE: 'chore: CHANGELOG.md updated'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
```

## Expected behavior

The changelog file should be updated after the workflow runs.

- OS: \ mac
- Browser \ chrome
- node \ 20
