### ISSUE TITLE
[question] Not working on private repos

### ISSUE THREAD

**Issue by Dufran** [BobAnkh/auto-generate-changelog#55]
Hello can you please tell if it should work on private repo?

**Comment by BobAnkh** [comment]
@Dufran 

Hello, thank you for using it. I can tell you that it can work on private repo. I have tested it.

![image](https://user-images.githubusercontent.com/44333669/118287403-01d37a80-b506-11eb-857b-adc3d43404fd.png)

![image](https://user-images.githubusercontent.com/44333669/118287439-09931f00-b506-11eb-977b-23d8eef2bf29.png)

Here is my configuration:

```yaml
name: Generate changelog
on:
  release:
    types: [created, edited]
  push:
    branches: 
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: BobAnkh/auto-generate-changelog@master
      with:
        REPO_NAME: 'BobAnkh/test-action'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: '/CHANGELOG.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
```

Make sure you configure it right. Please let me know if you have any question.
