### ISSUE TITLE
[bug] make it so that the action can submit a pull request to update the changelog

### ISSUE THREAD

**Issue by mmattbtw** [BobAnkh/auto-generate-changelog#78]
## Is your feature request related to a problem? Please describe

My problem is that my main branch is protected with some required statuses that much be passed. The action tries to push it to the branch directly instead of using a pull request to submit new changes. Which gives this error:
```
github.GithubException.GithubException: 409 {"message": "Could not update file: 2 of 2 required status checks are expected. Changes must be made through a pull request.", "documentation_url": "docs.github.com/articles/about-protected-branches"}
```

## Description of the new feature/enhancement

I would want the action to either submit a new pull request to update the changelog, or to update the changelog inside of the pull request itself.

## Proposed technical implementation details (optional)

A clear and concise description of any solutions you've considered.

**Comment by BobAnkh** [comment]
Hi, I want to know if the option `BRANCH` and `PULL_REQUEST` can not be directly used in your case?

![image](https://user-images.githubusercontent.com/44333669/147628799-3841c94c-3dcb-46bd-afba-b0fb19d92e18.png)

**Comment by mmattbtw** [comment]
I just tested this out, and it didn't work
https://github.com/mmattDonk/AI-TTS-Donations/blob/9a7175789f9407e63ed1a7ca20b9065bcc1183f1/.github/workflows/changelog.yml#L20-L27

**Comment by BobAnkh** [comment]
Ok, I think it is my fault that I didn't explain how to use this feature clearly.

This is your originnal workflow:

```yaml
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: BobAnkh/auto-generate-changelog@master
      with:mmattbtw, 3 months ago: • chore(workflows): Added all workflows
        REPO_NAME: 'mmattDonk/AI-TTS-Donations'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}matt, 9 hours ago: • Update changelog.yml
        PATH: '/CHANGELOG.md'mmattbtw, 3 months ago: • chore(workflows): Added all workflows
        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
        BRANCH: ''matt, 2 hours ago: • Update changelog.yml
        PULL_REQUEST: 'true'
```

Here you should specify the pull request from what `BRANCH` to what `PULL_REQUEST` branch. For example, set `BRANCH` to `docs/changelog` and set `PULL_REQUEST` to `main` and you will get a pull request opened from `docs/changelog` to `main`.

```diff
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: BobAnkh/auto-generate-changelog@master
      with:
        REPO_NAME: 'mmattDonk/AI-TTS-Donations'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: 'CHANGELOG.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
-        BRANCH: ''
+       BRANCH: 'docs/changelog'
-        PULL_REQUEST: 'true'
+       PULL_REQUEST: 'main'
```

Use `BRANCH`  to specify where you want to push your changelog first, and use PULL_REQUEST to specify the target branch you want to open a pr.
